export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const BEGIN_AJAX_ERROR = 'BEGIN_AJAX_ERROR';

export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';

export const LOAD_JOGGING_TIMES_SUCCESS = 'LOAD_JOGGING_TIMES_SUCCESS';
export const CREATE_JOGGING_TIME_SUCCESS = 'CREATE_JOGGING_TIME_SUCCESS';
export const UPDATE_JOGGING_TIME_SUCCESS = 'UPDATE_JOGGING_TIME_SUCCESS';
export const DELETE_JOGGING_TIME_SUCCESS = 'DELETE_JOGGING_TIME_SUCCESS';
export const CLEAR_JOGGING_TIMES_SUCCESS = 'CLEAR_JOGGING_TIMES_SUCCESS';

export const GET_JOGGING_TIMES_BY_USER_SUCCESS = 'GET_JOGGING_TIMES_BY_USER_SUCCESS';
export const GET_JOGGING_TIMES_BY_USER_ERROR = 'GET_JOGGING_TIMES_BY_USER_ERROR';
export const CREATE_JOGGING_TIME_BY_USER_SUCCESS = 'CREATE_JOGGING_TIME_BY_USER_SUCCESS';
export const UPDATE_JOGGING_TIME_BY_USER_SUCCESS = 'UPDATE_JOGGING_TIME_BY_USER_SUCCESS';
export const DELETE_JOGGING_TIME_BY_USER_SUCCESS = 'DELETE_JOGGING_TIME_BY_USER_SUCCESS';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const GET_USER_ROLE_SUCCESS = 'GET_USER_ROLE_SUCCESS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_ERROR = 'LOAD_USERS_ERROR';

export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_BY_USER_SUCCESS = 'CHANGE_PASSWORD_BY_USER_SUCCESS';

export const AUTHENTICATED_USER_SUCCESS = 'AUTHENTICATED_USER_SUCCESS';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

export const LOAD_AVG_SPEED_REPORT_SUCCESS = 'LOAD_AVG_SPEED_REPORT_SUCCESS';
